# Generated by Django 3.2.9 on 2021-12-18 23:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0013_alter_incidente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtenderIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default=datetime.datetime.now, null=True)),
                ('fecha', models.DateField(default=datetime.date.today, null=True)),
                ('observaciones', models.CharField(max_length=255, null=True)),
                ('imagen_video', models.CharField(max_length=255, null=True)),
                ('false_alarma', models.BooleanField(default=False, null=True)),
                ('incidente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.incidente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
