# Generated by Django 3.2.8 on 2021-10-30 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('imagen_video', models.CharField(max_length=255, null=True)),
                ('latitud', models.CharField(max_length=100, null=True)),
                ('longitud', models.CharField(max_length=100, null=True)),
                ('hora', models.TimeField(default=datetime.time, null=True)),
                ('fecha', models.DateField(default=datetime.date.today, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('false_alarma', models.BooleanField(default=False, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Sin atender'), (1, 'Por Atender'), (2, 'Incidente Archivado')], default=0, null=True)),
            ],
        ),
    ]
