# Generated by Django 3.2.8 on 2021-10-30 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_incidente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='fecha',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
