# Generated by Django 3.2.8 on 2021-10-30 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211030_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='hora',
            field=models.TimeField(default=datetime.date.today, null=True),
        ),
    ]
