# Generated by Django 3.2.8 on 2021-10-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_incidente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tipoincidente'),
        ),
    ]
