# Generated by Django 3.2.9 on 2021-11-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20211030_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidente',
            options={'permissions': (('listado_incidentes', 'Retorna el listado de Incidentes'), ('reportar_incidentes', 'Puede reportar incidentes'))},
        ),
    ]
