# Generated by Django 3.2.9 on 2021-11-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_incidente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidente',
            options={'permissions': (('dashboard_ciudadano', 'Acceso a la pantalla de inicio de usuario ciudadano'), ('listado_incidentes', 'Retorna el listado de Incidentes'), ('reportar_incidentes', 'Puede reportar incidentes'), ('mi_historial_incidentes', 'Listado de mis incidentes reportados'), ('mapa_incidentes', 'Visualización de Mapa de incidentes'), ('mapa_predictivo_incidentes', 'Visualización de Mapa predictivo'))},
        ),
    ]
